### ISSUE TITLE
Vector db implementation

### ISSUE THREAD

**Issue by ziad-kamel** [ziad-kamel/Graduation-Project#26]
we want to store the meaning of the notes(Embedding) so we want to make the connection with pinecone

METRIC : cosine (the cosine metric is a way to measure the similarity between two vectors)

DIMENSIONS: 1536 (1536 is a common dimensionality used in large language models (LLMs) like OpenAI's Ada-002, which often generate these embeddings)

CLOUD: gcp-starter

**Comment by yrai01** [comment]
bug #26
